### ISSUE TITLE
check_process fails

### ISSUE THREAD

**Issue by ishirav** [EgorLu/lsm#1]
Which version of psutil are you using? With v5.4.3 I get this error:
`Traceback (most recent call last):
  File "lsm.py", line 33, in <module>
    monitor.main()
  File "/tmp/lsm/lsm/monitor.py", line 389, in main
    status_report = check_status()
  File "/tmp/lsm/lsm/monitor.py", line 93, in check_status
    sys_scan = system_scan()
  File "/tmp/lsm/lsm/monitor.py", line 61, in system_scan
    "processes": scan_processes(),
  File "/tmp/lsm/lsm/monitor.py", line 54, in scan_processes
    if not check_process(process):
  File "/tmp/lsm/lsm/monitor.py", line 47, in check_process
    for p in psutil.process_iter(attrs=['name']):
TypeError: process_iter() takes no arguments (1 given)
`

**Comment by EgorLu** [comment]
Didn't see your reply here.
I've tested the setup on numerous machines today and found out that
python2.7 needs to be specified when running setup.py.

**Comment by ishirav** [comment]
I do use python 2.7, but what version of psutil do you have?

**Comment by EgorLu** [comment]
It's 5.4.3

**Comment by EgorLu** [comment]
Since we know that it was an issue with a wrong psutils version intalled, I resolve this issue.
